### ISSUE TITLE
Did you contact Threema for that?

### ISSUE THREAD

**Issue by rugk** [bitbatter/Threematrix#1]
I know you write there is no "no connection or affiliation with Threema or Threema GmbH.", but did you contact them to make sure what you are doing is okay?

AFAIK from my experience I can say they are pretty open about that, also your mentioned alternatives had contact with Threema so well…

**Comment by pReya** [comment]
Hey @rugk sorry for the late reply. Somehow I did not receive a notification about this new issue.

We've now added a little bit more information about the legal / business model situation in this [wiki page](https://github.com/bitbatter/Threematrix/wiki/Legal-thoughts-and-Threema's-business-model). So I will close this Issue now. Feel free to join the [discussion around this](https://github.com/bitbatter/Threematrix/discussions/2).
